#ifndef YCH_TOOLS_IMGTOOL_ROUTINES_H
#define YCH_TOOLS_IMGTOOL_ROUTINES_H

#include "RoutineLib.h"

EXTERN_ROUTINE_HANDLER(Routine_MakeStandard);
EXTERN_ROUTINE_HANDLER(Routine_ReadMBR);
EXTERN_ROUTINE_HANDLER(Routine_ReadGPT);

#endif // !YCH_TOOLS_IMGTOOL_ROUTINES_H
