#ifndef YCH_KERNEL_CORE_PRIVATE_MELTDOWNCODES_H
#define YCH_KERNEL_CORE_PRIVATE_MELTDOWNCODES_H

#include <stdint.h>

// `meltdown codes are unsigned 64-bit integers. this is standard.`
typedef uint64_t meltdowncode_t;

#define KR_CATEGORY_MELTDOWN_CODE_PROCESSOR 0x1000
#define KR_CATEGORY_MELTDOWN_CODE_MEMORY    0x2000
#define KR_CATEGORY_MELTDOWN_CODE_IO        0x3000
#define KR_CATEGORY_MELTDOWN_CODE_DEBUG     0x4000

/** PROCESSOR */
#define KR_MELTDOWN_CODE_CRITICAL_PROCESSOR_INTERRUPT (KR_CATEGORY_MELTDOWN_CODE_PROCESSOR +    1)

/** DEBUG */
#define KR_MELTDOWN_CODE_GENERAL_DEBUG        (KR_CATEGORY_MELTDOWN_CODE_DEBUG +    1)
#define KR_MELTDOWN_CODE_KERNEL_START_RETURNS (KR_CATEGORY_MELTDOWN_CODE_DEBUG +    2)

#endif // !YCH_KERNEL_CORE_PRIVATE_MELTDOWNCODES_H
